= RESTEasy Jakarta RESTful Web Services TCK

This project will run https://resteasy.dev[RESTEasy] in https://wildfly.org[WildFly] against the
https://jakarta.ee/specifications/restful-ws/[Jakarta REST] TCK.

You can run SE tests only with the `-Pse-only` Maven profile.

== Executing the TCK

You can run the TCK with Maven from the root project. The first module, `resteasy-tck-setup`, will download and install
the Jakarta REST TCK artifacts. The next project, `resteasy-tck-runner`, will provision a WildFly server if the
`JBOSS_HOME` environment variable is not set and run the TCK.

----
mvn clean verify
----

You can turn on trace logging for the TCK with the `-Dtck.log.trace=true` system property.

----
mvn clean verify -Dtck.log.trace=true
----

To run an individual test you can use the failsafe plugin property `-Dit.test=YourTestIT`.

----
mvn clean verify -Dit.test=UriBuilderIT
----

To override the RESTEasy version to test with you can pass the `-Dversion.org.jboss.resteasy` system property. To
override the WildFly version pass the `-Dversion.org.wildfly` system property.

----
mvn clean verify -Dversion.org.jboss.resteasy=6.1.0-SNAPSHOT -Dversion.org.wildfly=27.0.0.Beta1-SNAPSHOT
----